//VMBRSCON2
function contentAd5086() {var line = "";line += '<div id="ac_5086">';
line += '    <div class="ac_header_title">Sponsored From Around the Web</div>';
line += '        <div class="ac_adbox">';
line += '            <div class="ac_adbox_inner">';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1044\', \'4\', \'3626\', \'1114\')" onmousedown="this.href=\'http://howlifeworks.com/shopping/How_to_Wear_Kate_Bosworths_Jewelry_83?ag_id=1044&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1114\';return true;" href="http://howlifeworks.com/shopping/How_to_Wear_Kate_Bosworths_Jewelry_83?ag_id=1044&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1114">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/jewelmintwomanshowinglegs150x150.jpg" alt="Why Jewelry Lovers are Flipping for This New Store" class="ac_image" title="Why Jewelry Lovers are Flipping for This New Store" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1044\', \'4\', \'3626\', \'1114\')" onmousedown="this.href=\'http://howlifeworks.com/shopping/How_to_Wear_Kate_Bosworths_Jewelry_83?ag_id=1044&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1114\';return true;" href="http://howlifeworks.com/shopping/How_to_Wear_Kate_Bosworths_Jewelry_83?ag_id=1044&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1114">Why Jewelry Lovers are Flipping for This New Store</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1307\', \'4\', \'3626\', \'783\')" onmousedown="this.href=\'http://howlifeworks.com/technology/Explanation_How_Brain_Training_Can_Make_You_Significantly_Smarter_669?ag_id=1307&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=783\';return true;" href="http://howlifeworks.com/technology/Explanation_How_Brain_Training_Can_Make_You_Significantly_Smarter_669?ag_id=1307&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=783">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/Lumosity_Brain_Control.JPG" alt="How to Exercise Your Brain to Make It Strong" class="ac_image" title="How to Exercise Your Brain to Make It Strong" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1307\', \'4\', \'3626\', \'783\')" onmousedown="this.href=\'http://howlifeworks.com/technology/Explanation_How_Brain_Training_Can_Make_You_Significantly_Smarter_669?ag_id=1307&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=783\';return true;" href="http://howlifeworks.com/technology/Explanation_How_Brain_Training_Can_Make_You_Significantly_Smarter_669?ag_id=1307&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=783">How to Exercise Your Brain to Make It Strong</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'166\', \'4\', \'3626\', \'433\')" onmousedown="this.href=\'http://howlifeworks.com/travel/VTG_joy_of_cruising?ag_id=166&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=433\';return true;" href="http://howlifeworks.com/travel/VTG_joy_of_cruising?ag_id=166&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=433">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/VTG_Sexy.JPG" alt="How Cruise Lines Fill All Those Unsold Cabins" class="ac_image" title="How Cruise Lines Fill All Those Unsold Cabins" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'166\', \'4\', \'3626\', \'433\')" onmousedown="this.href=\'http://howlifeworks.com/travel/VTG_joy_of_cruising?ag_id=166&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=433\';return true;" href="http://howlifeworks.com/travel/VTG_joy_of_cruising?ag_id=166&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=433">How Cruise Lines Fill All Those Unsold Cabins</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1320\', \'4\', \'3626\', \'424\')" onmousedown="this.href=\'http://howlifeworks.com/shopping/What_Is_The_Best_NonPrescription_Eyelash_Enhancer_581?ag_id=1320&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=424\';return true;" href="http://howlifeworks.com/shopping/What_Is_The_Best_NonPrescription_Eyelash_Enhancer_581?ag_id=1320&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=424">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/SmartLashlg_eyelash_long.JPG" alt="How to Get Freakishly Long Eyelashes in 7 Days" class="ac_image" title="How to Get Freakishly Long Eyelashes in 7 Days" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1320\', \'4\', \'3626\', \'424\')" onmousedown="this.href=\'http://howlifeworks.com/shopping/What_Is_The_Best_NonPrescription_Eyelash_Enhancer_581?ag_id=1320&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=424\';return true;" href="http://howlifeworks.com/shopping/What_Is_The_Best_NonPrescription_Eyelash_Enhancer_581?ag_id=1320&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=424">How to Get Freakishly Long Eyelashes in 7 Days</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1138\', \'4\', \'3626\', \'526\')" onmousedown="this.href=\'http://howlifeworks.com/health_beauty/A_New_Solution_That_Stops_Snoring_and_Lets_You_Sleep_284?ag_id=1138&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=526\';return true;" href="http://howlifeworks.com/health_beauty/A_New_Solution_That_Stops_Snoring_and_Lets_You_Sleep_284?ag_id=1138&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=526">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/SnoreStrap Image_Large.JPG" alt="A New Solution That Stops Snoring and Lets You Sleep" class="ac_image" title="A New Solution That Stops Snoring and Lets You Sleep" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1138\', \'4\', \'3626\', \'526\')" onmousedown="this.href=\'http://howlifeworks.com/health_beauty/A_New_Solution_That_Stops_Snoring_and_Lets_You_Sleep_284?ag_id=1138&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=526\';return true;" href="http://howlifeworks.com/health_beauty/A_New_Solution_That_Stops_Snoring_and_Lets_You_Sleep_284?ag_id=1138&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=526">A New Solution That Stops Snoring and Lets You Sleep</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1275\', \'4\', \'3626\', \'1030\')" onmousedown="this.href=\'http://howlifeworks.com/health_beauty/How_to_Quickly_Boost_Your_Testosterone_for_Increased_Performance_441?ag_id=1275&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1030\';return true;" href="http://howlifeworks.com/health_beauty/How_to_Quickly_Boost_Your_Testosterone_for_Increased_Performance_441?ag_id=1275&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1030">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/ginsengrootontable150x150.jpg" alt="This New Natural Testosterone Booster Has Men Everywhere Raving" class="ac_image" title="This New Natural Testosterone Booster Has Men Everywhere Raving" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1275\', \'4\', \'3626\', \'1030\')" onmousedown="this.href=\'http://howlifeworks.com/health_beauty/How_to_Quickly_Boost_Your_Testosterone_for_Increased_Performance_441?ag_id=1275&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1030\';return true;" href="http://howlifeworks.com/health_beauty/How_to_Quickly_Boost_Your_Testosterone_for_Increased_Performance_441?ag_id=1275&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1030">This New Natural Testosterone Booster Has Men Everywhere Raving</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1154\', \'4\', \'3626\', \'410\')" onmousedown="this.href=\'http://howlifeworks.com/finance/How_Small_Investors_are_Making_Huge_Returns_Trading_Penny_Stocks_105?ag_id=1154&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=410\';return true;" href="http://howlifeworks.com/finance/How_Small_Investors_are_Making_Huge_Returns_Trading_Penny_Stocks_105?ag_id=1154&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=410">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/PennyStock_TestImage3_ManWomanAirplane.JPG" alt="How Penny Stocks Create Millionaires Every Day" class="ac_image" title="How Penny Stocks Create Millionaires Every Day" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1154\', \'4\', \'3626\', \'410\')" onmousedown="this.href=\'http://howlifeworks.com/finance/How_Small_Investors_are_Making_Huge_Returns_Trading_Penny_Stocks_105?ag_id=1154&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=410\';return true;" href="http://howlifeworks.com/finance/How_Small_Investors_are_Making_Huge_Returns_Trading_Penny_Stocks_105?ag_id=1154&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=410">How Penny Stocks Create Millionaires Every Day</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'333\', \'4\', \'3626\', \'1014\')" onmousedown="this.href=\'http://howlifeworks.com/technology/faster_pc_v2?ag_id=333&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1014\';return true;" href="http://howlifeworks.com/technology/faster_pc_v2?ag_id=333&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1014">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/square/aronewtestpc150x150.jpg" alt="How to Speed Up Your PC - Tricks Manufacturers Hate" class="ac_image" title="How to Speed Up Your PC - Tricks Manufacturers Hate" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'333\', \'4\', \'3626\', \'1014\')" onmousedown="this.href=\'http://howlifeworks.com/technology/faster_pc_v2?ag_id=333&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1014\';return true;" href="http://howlifeworks.com/technology/faster_pc_v2?ag_id=333&wid=D0A57B0F-2FC6-4029-AE64-27411BB0C956&did=3626&cid=1005&si_id=1014">How to Speed Up Your PC - Tricks Manufacturers Hate</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1000655\', \'3\', \'3626\', \'\')" onmousedown="this.href=\'http://www.consumer-car-reviews.com/top-10-hottest-female-race-car-drivers/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars\';return true;" href="http://www.consumer-car-reviews.com/top-10-hottest-female-race-car-drivers/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/images/7a36a1dcdc8a040791565a0e77de40cd_73018df2887e1b7d96e94538fd26527b.jpg" alt="Top 10 Hottest Female Race Car Drivers" class="ac_image" title="Top 10 Hottest Female Race Car Drivers" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1000655\', \'3\', \'3626\', \'\')" onmousedown="this.href=\'http://www.consumer-car-reviews.com/top-10-hottest-female-race-car-drivers/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars\';return true;" href="http://www.consumer-car-reviews.com/top-10-hottest-female-race-car-drivers/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars">Top 10 Hottest Female Race Car Drivers</a>';
line += '</div>';
line += '</div>';
line += '<div class="ac_container">';
line += '<a class="ac_image_link" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1000210\', \'3\', \'3626\', \'\')" onmousedown="this.href=\'http://www.consumer-car-reviews.com/nicest-cars-in-2013-2/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars\';return true;" href="http://www.consumer-car-reviews.com/nicest-cars-in-2013-2/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars">';
line += '<img height="120" width="120" src="http://contentad.blob.core.windows.net/images/d45d529a5013a499f050eb74ab7163a5_73018df2887e1b7d96e94538fd26527b.jpg" alt="Nicest Cars in 2013" class="ac_image" title="Nicest Cars in 2013" />';
line += '</a>';
line += '<div class="ac_title_wrapper">';
line += '<a class="ac_title" rel="nofollow" target="_blank" onclick="javascript:trackOutboundClick(\'1727864\', \'5086\', \'1000210\', \'3\', \'3626\', \'\')" onmousedown="this.href=\'http://www.consumer-car-reviews.com/nicest-cars-in-2013-2/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars\';return true;" href="http://www.consumer-car-reviews.com/nicest-cars-in-2013-2/?utm_source=content-ad&utm_medium=cpc&utm_campaign=cars">Nicest Cars in 2013</a>';
line += '</div>';
line += '</div>';
line += '<img src="http://api.content.ad/pixel.gif?s=VMBRSCON2&cid=1414865&ip=74.110.61.237&cb=635020332969286056" height="1" width="1" />';
line += '            </div>';
line += '<div style="clear:both;"></div>';
line += '<div class="ac_credit"><a href="https://www.content.ad/AboutUs.aspx" target="_blank" rel="nofollow">?</a></div>';
line += '<div class="ac_modal_shading"></div>';
line += '<div class="ac_credit_copy"><div class="ac_credit_logo"><img src="http://api.content.ad/Images/c_ad_logo.png" /></div>These content links are provided by Content.ad. Both Content.ad and the web site upon which the links are displayed may receive compensation when readers click on these links. Some of the content you are redirected to may be sponsored content. View our privacy policy <a href="https://www.content.ad/privacy.aspx" target="_blank" rel="nofollow">here</a>.<br /><br />To learn how you can use Content.ad to drive visitors to your content or add this service to your site, please contact us at <a href="mailto:info@content.ad" rel="nofollow">info@content.ad</a>.</div>';
line += '        </div>';
line += '    <div style="clear:both;"></div>';
line += '</div>';
line += '';
line += '<style type="text/css" id="ac_5086_css">';
line += '/* Easy */';
line += '';
line += '#ac_5086 {';
line += '    clear:both;';
line += '    display:block;';
line += '    text-align:left;';
line += '    margin:20px 0 30px 15px;';
line += '    position:relative;';
line += '    }';
line += '';
line += '#ac_5086 .ac_header_title {';
line += '    margin:0px;';
line += '    border:none;';
line += '    direction:ltr;';
line += '    text-align:left;';
line += '    vertical-align:middle;';
line += '    padding:0;';
line += '    font-size:14px;';
line += '    font-weight:bold;';
line += '    word-wrap:break-word;';
line += '    font-family:verdana;';
line += '    }';
line += '';
line += '#ac_5086 .ac_adbox {';
line += '    width:100%;';
line += '    position:relative;';
line += '    display:block;';
line += '    clear:both;';
line += '    text-align:left;';
line += '    text-decoration:none;';
line += '    }';
line += '';
line += '#ac_5086 .ac_image {';
line += '    width:120px;';
line += '    height:120px;';
line += '    border:none !important;';
line += '    margin:0px !important;';
line += '    display:block;';
line += '    padding:0px !important;';
line += '    max-width:100%;';
line += '    }';
line += '';
line += '#ac_5086 .ac_container {';
line += '    display:inline-block;';
line += '    *display:inline;';
line += '    zoom:1;';
line += '    vertical-align:top;';
line += '    padding-right:5px;';
line += '    margin-top:15px;';
line += '    }';
line += '';
line += '#ac_5086 .ac_container:hover .ac_image_link {';
line += '    border:1px solid #333;';
line += '    padding:2px;';
line += '    }';
line += '';
line += '#ac_5086 .ac_container:hover .ac_title_wrapper .ac_title {';
line += '    text-decoration:underline;';
line += '    }';
line += '';
line += '#ac_5086 .ac_container a {';
line += '    display:block;';
line += '    direction:ltr;';
line += '    text-align:left;';
line += '    text-decoration:none;';
line += '    }';
line += '';
line += '#ac_5086 .ac_title_wrapper {';
line += '    width:120px;';
line += '    padding-top:4px;';
line += '    }';
line += '';
line += '#ac_5086 .ac_title_wrapper .ac_title {';
line += '    margin:0px;';
line += '    border:none;';
line += '    direction:ltr;';
line += '    text-align:left;';
line += '    vertical-align:middle;';
line += '    word-wrap:break-word;';
line += '    width:100%;';
line += '    padding:0px;';
line += '    font-size:100%;';
line += '    font-weight:bold;';
line += '    line-height:1.4;';
line += '    color: #02446a;';
line += '    }';
line += '';
line += '#ac_5086 .ac_referrer {';
line += '    font-size:10px;';
line += '    font-weight:normal;';
line += '    font-style:italic;';
line += '    color:#888;';
line += '    word-wrap:break-word;';
line += '    line-height:150%;';
line += '    }';
line += '';
line += '#ac_5086 a.ac_image_link {';
line += '    border:1px solid #aaa;';
line += '    display:inline-block;';
line += '    *display:inline;';
line += '    zoom:1;';
line += '    padding:2px;';
line += '    margin-right:10px;';
line += '    position:relative;';
line += '    overflow:hidden;';
line += '    width:120px;';
line += '    height:120px;';
line += '    }';
line += '';
line += '#ac_5086 .ac_container a.ac_image_link .ac_sponsored {';
line += '    position:absolute;';
line += '    bottom:2px;';
line += '    right:2px;';
line += '    padding:0 1px 0 4px;';
line += '    background-color:#000;';
line += '    opacity:0.5;';
line += '    font-size:9px;';
line += '    text-transform:capitalize;';
line += '    letter-spacing:1px;';
line += '    color:#fff;';
line += '    line-height:17px;';
line += '    border-radius:5px 0 0 0;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit {';
line += '    position:absolute;';
line += '    bottom:-15px;';
line += '    right:0;';
line += '    font-size:11px;';
line += '    color:#999;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit a {';
line += '    display:inline-block;';
line += '    background-color:#707070;';
line += '    opacity:0.5;';
line += '    padding:0 5px;';
line += '    margin-left:2px;';
line += '    border-radius:15px;';
line += '    font-size:12px;';
line += '    font-weight:bold;';
line += '    color:#fff;';
line += '    line-height:17px;';
line += '    text-decoration:none;';
line += '    margin-right: 15px;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit_copy {';
line += '    position:fixed;';
line += '    text-align:left;';
line += '    width:40%;';
line += '    left:0;';
line += '    color:#333;';
line += '    font-family:arial,sans-serif;';
line += '    font-size:12px;';
line += '    padding:2%;';
line += '    background-color:#fff;';
line += '    margin:0 28%;';
line += '    top:25%;';
line += '    display:none;';
line += '    z-index:1000000;';
line += '    box-shadow:5px 5px 5px rgba(0,0,0,0.7);';
line += '    border:1px solid #000;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit_logo {';
line += '    width:50%;';
line += '    max-width:300px;';
line += '    margin:0 auto 24px;';
line += '    text-align:center;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit_logo img {';
line += '    width:100%;';
line += '    }';
line += '';
line += '#ac_5086 .ac_credit_copy a {';
line += '    color:#F06924;';
line += '    text-decoration:underline;';
line += '    }';
line += '';
line += '#ac_5086 a.ac_credit_copy_exit {';
line += '    position:absolute;';
line += '    top:-10px;';
line += '    right:-10px;';
line += '    background-color:#fff;';
line += '    border:1px solid #000;';
line += '    border-radius:15px 15px 15px 15px;';
line += '    color:#000;';
line += '    display:inline-block;';
line += '    font-size:15px;';
line += '    font-weight:bold;';
line += '    line-height:18px;';
line += '    padding:0 5px;';
line += '    text-decoration:none;';
line += '    box-shadow:3px 3px 3px rgba(0,0,0,0.3);';
line += '    }';
line += '';
line += '#ac_5086 .ac_modal_shading {';
line += '    display:none;';
line += '    position:fixed;';
line += '    top:0;';
line += '    left:0;';
line += '    width:100%;';
line += '    height:100%;';
line += '    background-color:rgba(0,0,0,0.75);';
line += '    z-index:999999;';
line += '    }';
line += '</style>';
line += '';
return line;}    function sortNumber(a, b) {
        return b - a;
    }

    var jQueryScriptOutputted = false;
    function initJQuery5086() {
        if (typeof (jQuery) == 'undefined') {
            if (!jQueryScriptOutputted) {
                jQueryScriptOutputted = true;
                var s = document.createElement('script');
                s.type = 'text/javascript';
                s.async = true;
                s.src = "//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js";
                var x = document.getElementsByTagName('script')[0];
                x.parentNode.insertBefore(s, x);
            }
            setTimeout("initJQuery5086()", 50);
        } else {
            sponsoredAnimation5086();
            initCredit5086();
        }
    }

    function sponsoredAnimation5086() {
        jQuery("#ac_5086 .ac_container").hover(
            function() {
                jQuerythisIndex = jQuery(this).index() + 1;
                jQuery('#ac_5086 .ac_container:nth-child(' + jQuerythisIndex + ') a.ac_image_link .ac_sponsored').animate({
                    opacity: 0.85
                }, 500, 'linear');
            },
            function() {
                jQuerythisIndex = jQuery(this).index() + 1;
                jQuery('#ac_5086 .ac_container:nth-child(' + jQuerythisIndex + ') a.ac_image_link .ac_sponsored').animate({
                    opacity: 0.5
                }, 500, 'linear');
            }
        );
    }

    function initCredit5086() {
        jQuery("#ac_5086 .ac_credit_copy").prepend("<a href='#' class='ac_credit_copy_exit'>X</a>");
        jQuery("#ac_5086 .ac_credit a").click(function() {
            if (jQuery("#ac_5086 .ac_credit_copy").css('display') == 'none') {
                jQuery("#ac_5086 .ac_modal_shading").show();
                jQuery("#ac_5086 .ac_credit_copy").fadeIn('400');
            }
            return false;
        });
        jQuery("#ac_5086 .ac_credit_copy_exit").click(function() {
            jQuery("#ac_5086 .ac_modal_shading").hide();
            jQuery("#ac_5086 .ac_credit_copy").hide();
            return false;
        });
    }


function trackOutboundClick(hostUrlId, widgetId, urlId, typeId, domainId, subjectImageId) {
    var img = new Image(1,1);  
    img.src = 'http://api.content.ad/Lib/TrackOutboundClick.aspx?hid=' + hostUrlId + '&wid=' + widgetId + '&uid=' + urlId + '&type=' + typeId + '&did=' + domainId + '&sid=' + subjectImageId;
}